package xyz.devcmb.tumblers.engine

enum class Flag {
    DISABLE_FALL_DAMAGE,
    DISABLE_PVP,
    ENABLE_HUNGER,
    ENABLE_ITEM_DROPS,
    ENABLE_LOCATOR_BAR,
    DISABLE_TNT_AUTO_EXPLODE,
    DISABLE_BLOCK_BREAKING
}