database:
  host:
  port:
  username:
  password:
  database:

event:
  event_mode: true
  cutscene:
    first: [1.13,198.19,14.26,-125.2,40.2]
  voting:
    quadrants:
      # x1,y1,z1,x2,y2,z2
      - [10,192,7,23,188,-6]
      - [10,192,9,23,188,22]
      - [8,192,9,8,188,9]
      - [8,192,7,8,188,7]
    logos:
      - [17, 198, 0]
      - [17, 198, 16]
      - [1, 198, 16]
      - [1, 198, 0]
    inactive_quadrant_material: GRAY_CONCRETE
    center: [9,196,8]

templates:
  # The path where all the template worlds are contained
  # Use & to refer to the plugin's data container (plugins/TreeTumblers in most cases)
  world_root: "&/templates/worlds"

lobby:
  world: hub
  position: [-20.0, 209.0, 5.0,-90.0,0.0]

# All games use the same format for their config, aside from the data fields
# Refer to the comments in the first game for usage in the others
games:
  crumble:
    # The path where all the maps are contained
    # This path is relative to the `world_root` config value
    worlds_folder: "crumble"
    max_kit_players: 2
    tnt_detonation_time: 80
    crumble_speed: 0.6
    round_length: 75
    kits:
      archer:
        punch_level: 2
        power_level: 3
        swiftness_ticks: 30
      bomber:
        nuke_explosion_ticks: 5
        nuke_radius: 7.0
        nuke_damage: 7
        blast_protection_level: 1
      fisher:
        trident_loyalty_level: 2
        trident_damage: 5.0
        trident_attack_speed: 1.1
      ninja:
        invisibility_duration: 80
        smoke_duration: 100
        smoke_size: 2.5
      sorcerer:
        poison_duration: 70
        heal_hearts: 2
        heal_duration: 60
      warrior:
        blindness_ticks: 50
      worker:
        megamine_duration: 150
        efficiency_duration: 200
    maps:
      warfare:
        world: "crumble_warfare"
        data:
          map_size: 70
          kill_height: 86
          spawns:
            pregame: [-32.5,100.0,-33.5]
            ingame:
              arena1:
                # The first set of spawns for the first team on this map
                # It looks so bad but who caresssss
                - [
                  [ -38.5,100.0,-43.5 ],
                  [ -38.5,100.0,-41.5 ],
                  [ -40.5,100.0,-39.5 ],
                  [ -42.5,100.0,-39.5 ]
                ]
                # The second set of spawns for the second team on this map
                - [
                  [ -32.5,100.0,-29.5 ],
                  [ -32.5,100.0,-31.5 ],
                  [ -30.5,100.0,-33.5 ],
                  [ -28.5,100.0,-33.5 ]
                ]
              arena2:
                - [
                  [-538.5, 100.0, 456.5],
                  [-538.5, 100.0, 458.5],
                  [-540.5, 100.0, 460.5],
                  [-542.5, 100.0, 460.5]
                ]
                - [
                  [-532.5, 100.0, 470.5],
                  [-532.5, 100.0, 468.5],
                  [-530.5, 100.0, 466.5],
                  [-528.5, 100.0, 466.5]
                ]
              arena3:
                - [
                  [471.5, 100.0, -539.5],
                  [469.5, 100.0, -539.5],
                  [467.5, 100.0, -541.5],
                  [467.5, 100.0, -543.5]
                ]
                - [
                  [457.5, 100.0, -533.5],
                  [459.5, 100.0, -533.5],
                  [461.5, 100.0, -531.5],
                  [461.5, 100.0, -529.5]
                ]
              arena4:
                - [
                  [-542.5, 100.0, -533.5],
                  [-540.5, 100.0, -533.5],
                  [-538.5, 100.0, -531.5],
                  [-538.5, 100.0, -529.5]
                ]
                - [
                  [-528.5, 100.0, -539.5],
                  [-530.5, 100.0, -539.5],
                  [-532.5, 100.0, -541.5],
                  [-532.5, 100.0, -543.5]
                ]
          centers:
            arena1: [-35.5,103.0,-36.5]
            arena2: [-535.5,103.0,-463.5]
            arena3: [464.5,103.0,-536.5]
            arena4: [-535.5,103.0,-536.5]
            cutscene: [464.5,103.0,463.5]
          cutscene:
            # X,Y,Z,pitch,yaw
            start: [474.5,107.5,473.5,134.3,36.5]
            crumble_demonstration: [438.5,102.5,489.5,45.0,33.0]
            credit: [464.4,90.3,471.4,62.3,13.6]
          walls:
            # startX,startY,startZ,endX,endY,endZ
            - [0,115,-37,-72,99,-37]
            - [-500,115,463,-572,99,463]
            - [500,115,-537,428,99,-537]
            - [-500,115,-537,-572,99,-537]
  deathrun:
    worlds_folder: "deathrun"
    lives: 3
    maps:
      forest:
        world: "forest"
        data:
          spawns:
            main: [-4.5,63.0,15.5,-90.0,0.0]
            attacker: [2.5,67.0,2.5]
          cutscene:
            start: [36.84,61.84,21.5,155.7,9.3]
            trapper_showcase: [6.15,66.9,7.89,179.2,6.3]
            # Must be the first trap
            trap_showcase: [8.78,68.6,9.0,0.2,48.6]
            armor_stands:
              - [3,67,1]
              - [5,67,1]
              - [7,67,1]
              - [9,67,1]
            runner_score_showcase: [64.119,62.36,19.425,-122.6,5.7]
          gate_start: [-2,62,8]
          gate_end: [-2,62,21]
          point_display:
            pos: [ 71.25,63.12,14.81 ]
            yaw: 90
            scale: 5.0
          win_zone_start: [71,66,23]
          win_zone_end: [71,61,6]
          void_height: 48
          checkpoints:
            - start: [45,68,22]
              end: [45,61,7]
              respawn: [45,63,15,-90.0,0.0]
          traps:
            - id: "magma_fall"
              start: [-1,70,-2]
              end: [18,65,4]
              data:
                replace_type: STONE
                replace_start: [-1,61,22]
                replace_end: [18,61,7]
            - id: "beam_run"
              start: [ 19,70,-2 ]
              end: [ 43,65,4 ]
              data:
                blocks:
                  - [ 41,61,20 ]
                  - [ 41,61,19 ]
                  - [ 33,61,18 ]
                  - [ 33,61,17 ]
                  - [ 29,61,17 ]
                  - [ 29,61,16 ]
            - id: "happy_ghast"
              start: [43,70,-2]
              end: [67,65,4]
              data:
                ghasts:
                  - [50.47,57.71,10.05]
                  - [56.78,57.97,19.16]
                  - [62.36,58.03,10.16]
                  - [69.24,56.90,14.04]