database:
  host:
  port:
  username:
  password:
  database:

# All games use the same format for their config, aside from the data fields
# Refer to the comments in the first game for usage in the others
games:
  crumble:
    # The path where all the maps are contained
    # Use & to refer to the plugin's data container (plugins/TreeTumblers in most cases)
    worlds_folder: "&/templates/worlds/crumble"
    max_kit_players: 2
    kits:
      archer:
        punch_level: 2
        power_level: 3
        swiftness_ticks: 30
    maps:
      warfare:
        world: "crumble_warfare"
        data:
          spawns:
            pregame: [-32.5,79.0,-33.5]
            ingame:
              arena1:
                # The first set of spawns for the first team on this map
                # It looks so bad but who caresssss
                - [
                  [ -38.5,79.0,-43.5 ],
                  [ -38.5,79.0,-41.5 ],
                  [ -40.5,79.0,-39.5 ],
                  [ -42.5,79.0,-39.5 ]
                ]
                # The second set of spawns for the second team on this map
                - [
                  [ -32.5,79.0,-29.5 ],
                  [ -32.5,79.0,-31.5 ],
                  [ -30.5,79.0,-33.5 ],
                  [ -28.5,79.0,-33.5 ]
                ]

          cutscene:
            # X,Y,Z,pitch,yaw
            start: [-25.5,86.0,-26.5,134.5,35.4]